### PR TITLE
Quack

### LINKED ISSUE #432: `MatrixOperators` -> `Matrices`
So... now there are more than operators in `MatrixOperators` module.

Simple renaming of a module. Up for grabs!

Where to look for it: `Sources/Wrappers/AngouriMath.FSharp`

### PR DESCRIPTION
**Pull request by Happypig375**
Closes #432

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
🐷

**Comment by WhiteBlackGoose** [comment]
Pig can into tests

**Comment by Happypig375** [comment]
Ye with no s

**Comment by WhiteBlackGoose** [comment]
@Happypig375 thanks for your contribution! 🐷

**Pull request merged**
