### PR TITLE
Replaced Jupyter badge with .NET Interactive badge #545

### PR DESCRIPTION
**Pull request by mgnslndh**
This is a fix for #545.

Do you want the updated .PDN? Perhaps it could be added to a new folder in the root /Assets or /Branding?

Please add the hacktoberfest-accepted label to this PR if you find it useful.

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
Nice, but where did you take that notebook from?

**Comment by mgnslndh** [comment]
The [notebok ](https://github.com/dotnet/interactive/blob/main/assets/Polyglot%20Notebook.svg)is from the dotnet/interactive repo that you linked in the description.

**Comment by WhiteBlackGoose** [comment]
Ah, I see. Are we allowed to use it? Do we need to credit it somewhere?

**Comment by mgnslndh** [comment]
The repo is licensed under MIT so I guess we're good if we give them credit where that makes sense.

**Comment by mgnslndh** [comment]
Since AngouriMath is a library I think that attribution should be part of the documentation.

**Comment by WhiteBlackGoose** [comment]
For future reference: we reference .NET Interactive [here](https://github.com/asc-community/AngouriMathLab/blob/main/we-thank.md).

**Comment by WhiteBlackGoose** [comment]
Thanks

**Pull request merged**
