### PR TITLE
You need Java

### PR DESCRIPTION
**Pull request by Happypig375**

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
1) We shouldn't build the parser every time we build, so we don't really need Java. (we will remove it from the solution build script so it is only called when .g is changed)
2) The user doesn't need to add reference to PeterO Numbers to use AM if Im not mistaken

**Comment by Happypig375** [comment]
image

**Comment by Happypig375** [comment]
```
NU1105: Unable to find project information for 'C:\Users\hadri\Source\Repos\CSharpMath\AngouriMath\PeterONumbers\Numbers\Numbers.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.
NU1105: Unable to find project information for 'C:\Users\hadri\Source\Repos\CSharpMath\AngouriMath\PeterONumbers\Numbers\Numbers.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.
NU1105: Unable to find project information for 'C:\Users\hadri\Source\Repos\CSharpMath\AngouriMath\PeterONumbers\Numbers\Numbers.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.
NU1105: Unable to find project information for 'C:\Users\hadri\Source\Repos\CSharpMath\AngouriMath\PeterONumbers\Numbers\Numbers.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>------ Rebuild All started: Project: AngouriMath, Configuration: Debug Any CPU ------
1>C:\Users\hadri\Source\Repos\CSharpMath\AngouriMath\AngouriMath\AngouriMath.csproj : error NU1105: Unable to find project information for 'C:\Users\hadri\Source\Repos\CSharpMath\AngouriMath\PeterONumbers\Numbers\Numbers.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.
1>Done building project "AngouriMath.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Happypig375** [comment]
Of course you need to add `Numbers` to your solution.

**Comment by WhiteBlackGoose** [comment]
This should work now

**Comment by Happypig375** [comment]
Then we are left with
>(we will remove it from the solution build script so it is only called when .g is changed).

When .g is changed, we still need a Java runtime to run ANTLR. Otherwise, we will have unexpected outdated generated code. Therefore, contributors must still install a Java runtime.

**Comment by MomoDeve** [comment]
Generated code for Anltr is distributed along with all other source files. If somebody wants to change .g file, he runs antlr himself, then commit all files. Whats the problem?

**Comment by WhiteBlackGoose** [comment]
We might remove automated generating if we won't be able to come to a better solution

**Comment by WhiteBlackGoose** [comment]
Or partial solution: make it work on Windows (so on every change of .g antlr is called), but leave it to be run manually on other systems.

**Comment by Happypig375** [comment]
How would the "partial solution" work? How would you detect changes of .g automatically?

**Comment by WhiteBlackGoose** [comment]
We decided to remove the automatic compiling of .g . It is only needed for contributors who want to change the syntax, so most people shouldn't be required to install Java.

**Comment by Happypig375** [comment]
Alright then. This PR is now not needed.

**Pull request closed without merging**
