### PR TITLE
Update Copyright information from 2021 to 2022

### PR DESCRIPTION
**Pull request by bimal-parajuli**
Update the copyright information in all files in the directories and subdirectories recursively using bash stream editor - sed

Command used:
find . -type f -not -path '*/\.*' -exec sed -i 's/2021/2022/g' {} +

Number of files changed:
273
Number of replacements made:
275

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
Nice one. Could you also change it in editorconfig file?

**Comment by bimal-parajuli** [comment]
> Nice one. Could you also change it in editorconfig file?

Sure. I just skipped the hidden files. I'll do it now.

**Comment by bimal-parajuli** [comment]
@WhiteBlackGoose  I have made the necessary changes. 
Feel free to reach out in case of any other changes needed.

**Comment by WhiteBlackGoose** [comment]
Awesome, thanks!

**Review by WhiteBlackGoose — APPROVED** [review]

**Pull request merged**
