### PR TITLE
Expose OperatorSet construction where Eval() is not called automatically to match Entity operator behaviour

### PR DESCRIPTION
**Pull request by Happypig375**
Eval() can be called once only on the final result.

### CODE REVIEW

**Comment by Happypig375** [comment]
Judging by the usage, it seems that exposing OperatorSet methods is more appropriate.

**Comment by Happypig375** [comment]
Looks like `Eval` will need to be updated to support this. Hmm.

**Comment by WhiteBlackGoose** [comment]
Flow of thoughts :). But since all methods Or, And etc. are internal and only operators are exposed we know for sure that Eval has already been called for each child, no need to call it once again

**Comment by Happypig375** [comment]
We know that entities do not simplify automatically for arithmetic operators. `Eval` or `Simplify` should be called. Why don't sets exhibit this behaviour?

**Comment by WhiteBlackGoose** [comment]
Because unlike the expression trees, there's no such thing as a set tree. It's artificially created abstraction that people are not familiar with. At the same time, there expression trees for classic symbolic algebra formulas. I know what you are talking about, at the same time, those have to behave differently.

**Pull request closed without merging**
