### PR TITLE
Address comments and remove unused code

### LINKED ISSUE #148: Real negative numbers parentheses for power for LaTeX
```cs
var a = RealNumber.Create(-32.22145236223m);
var b = MathS.Pow(a, 4);
Console.WriteLine(b.Latexise());
```
Output:
```
{-32.22145236223}^{4}
```
Desired output:
```
{\left(-32.22145236223\right)}^{4}
```

### PR DESCRIPTION
**Pull request by Happypig375**
You merged before I could push lol

Fixes #148

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
Oops :), I even already fixed it. I thought you were unavailable so it was easier to fix it myself. Alright, I'll merge it once git will allow me

**Comment by Happypig375** [comment]
Closing and reopening to hopefully restart the merge check

**Comment by Happypig375** [comment]
@WhiteBlackGoose GitHub seems bugged. You may try merging in the Git command line.

**Comment by WhiteBlackGoose** [comment]
It's dead, we got to wait. It doesn't even run the CI

**Comment by Happypig375** [comment]
Yup... As I checked https://www.githubstatus.com/, GitHub Actions is experiencing an outage.

**Pull request merged**
