### PR TITLE
Boolean, Domains

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
It's an early pull-request, anybody is welcomed to see all the incoming changes

## Possible migration problems
1. `Number`, `Sumf`, ... `Function` now inherit `Continuous` which inherits `Entity`
2. `Eval` -> `EvalNumerical` (as `EvalBoolean` added)
3. `Evaluable` -> `EvaluableNumerical` (as `EvaluableBoolean` added)

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
Neither looks better that it is now. Though I will add a `Substitute((Variable var, Entity toSub)[] subs)`

**Comment by Happypig375** [comment]
Array requires linear lookup, Dictionary has constant lookup.

**Comment by Happypig375** [comment]
Even more, most cases it will be a lookup miss.

**Comment by WhiteBlackGoose** [comment]
Now it's unclear how we should implement design for Domains

**Comment by WhiteBlackGoose** [comment]
Design proposal:
1) `.WithDomain` for nodes when building an expression manually
2) `domain(node, Real)` for parsing from string

**Comment by WhiteBlackGoose** [comment]
Alright so now it should be somehow reviewed and soon merged. If I missed anything, please report.

**Pull request merged**
