### PR TITLE
oo * i -> oo i

### PR DESCRIPTION
**Pull request by Happypig375**
#107 strikes again

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
I will first fix my own mistakes that were made after merging the branches

**Comment by WhiteBlackGoose** [comment]
Those tests seem to be wrong. If you multiply infinity by a complex number, you get a complex number of two infinities in both axes

**Comment by Happypig375** [comment]
Then how would you create `\infty i` from `\infty` and `i`? From any perspective, that is implicit multiplication.

**Comment by Happypig375** [comment]
And the output of `\infty i` should be able to be the input with the same result.

**Comment by WhiteBlackGoose** [comment]
So far there's indeed no way of creating it through product. The easiest way to create it is to write
```cs
var re = Number.Create(0);
var im = Number.Create(RealNumber.UndefinedState.POSITIVE_INFINITY);
var num = Number.Create(re, im);
```
Maybe I will implement implicit conversion from UndefinedState into RealNumber.

**Comment by Happypig375** [comment]
@WhiteBlackGoose 
What you see: `∞ i`
What it means: `∞ × i`
But it actually evaulates to `-∞ + ∞ i`

**Comment by Happypig375** [comment]
And obviously `-∞ + ∞ i` ≠ `∞ i`

**Comment by WhiteBlackGoose** [comment]
Of course, because you multiply +inf by (0 + i), where product of any non-negative real number and +inf results in +oo. We can do 0 * (+oo) = 0, I will consider that

**Comment by Happypig375** [comment]
@WhiteBlackGoose No. You see, `∞ × ∞` is `∞`. However, if you add a zero: `(∞ + 0) × (∞ + 0)` = `∞∞ + 0∞ + 0∞ + 0` = `∞ + undefined + undefined + 0` = `undefined`.

**Comment by Happypig375** [comment]
@WhiteBlackGoose Failed tests will pass once #155 is merged into this PR.

**Comment by Happypig375** [comment]
Tests now pass

**Comment by WhiteBlackGoose** [comment]
Probably it makes sense now

**Pull request merged**
